(() => {
"use strict";
const $=id=>document.getElementById(id);
const canvas=$("gameCanvas"), ctx=canvas.getContext("2d");
const W=canvas.width,H=canvas.height;
const qs=new URLSearchParams(location.search);
const student={name:qs.get("name")||"PancaPath Explorer",code:qs.get("code")||"",route:qs.get("route")||"eksplorasi"};
const returnUrl=qs.get("return")||"../index.html#pancaQuest";
$("studentName").textContent=student.name;
const routeMeta={eksplorasi:["🟢 Jalur Eksplorasi","Petunjuk aktif lebih jelas"],penguatan:["🔵 Jalur Penguatan","Petunjuk tersedia saat dibutuhkan"],tantangan:["🟣 Jalur Tantangan","Tantangan lebih mandiri"]};
$("studentRoute").textContent=(routeMeta[student.route]||routeMeta.eksplorasi)[0];

let audioOn=true,audioCtx=null;
function beep(f=500,d=.08){if(!audioOn)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type='sine';g.gain.value=.035;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.stop(audioCtx.currentTime+d)}catch(e){}}

const keys={};let joy={x:0,y:0};let paused=true;let gameStarted=false;let modalOpen=false;let currentLevel=0;let xp=0;let hearts=3;let startTime=0;let hazardCooldown=0;
const player={x:480,y:465,r:17,speed:185,dir:0};
const state={level1:false,collect:new Set(),hazards:new Set(),level3:false,level4:false};
const actionData={action:"",actor:"",time:"",indicator:""};
let promptAction=null,promptLabel="";
const levels=[
 {name:"Sekolah • Kenali Nilainya",progress:25},
 {name:"Taman Nilai • Kumpulkan Nilai Baik",progress:50},
 {name:"Ruang Musyawarah • Pilih Solusi",progress:75},
 {name:"Kelas Aksi • Bangun Tindakan",progress:100}
];
const collectibles=[
 {x:210,y:300,label:"Gotong Royong",icon:"🤝"},{x:410,y:220,label:"Toleransi",icon:"❤️"},{x:640,y:330,label:"Musyawarah",icon:"🗣️"},{x:790,y:190,label:"Keadilan",icon:"⚖️"}
];
const hazards=[{x:315,y:390,label:"Egoisme"},{x:540,y:420,label:"Diskriminasi"},{x:735,y:400,label:"Intoleransi"}];

function show(el){el.classList.add('show')} function hide(el){el.classList.remove('show')}
function toast(t){const e=$("toast");e.textContent=t;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),1700)}
function updateHUD(){
 $("xpValue").textContent=xp;$("hearts").textContent='❤️'.repeat(hearts)+'🖤'.repeat(3-hearts);
 $("levelLabel").textContent=`LEVEL ${currentLevel+1}`;$("levelTitle").textContent=levels[currentLevel].name;$("levelProgress").style.width=`${levels[currentLevel].progress}%`;
}
function resetPlayer(){player.x=480;player.y=470;joy.x=joy.y=0;}
function nextLevel(){currentLevel=Math.min(3,currentLevel+1);resetPlayer();updateHUD();beep(760,.12);toast(`Level ${currentLevel+1} terbuka!`)}
function addXp(n){xp=Math.max(0,Math.min(100,xp+n));updateHUD();beep(800,.08)}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function label(text,x,y,bg='#fff',fg='#172554'){ctx.font='700 13px system-ui';const m=ctx.measureText(text);rounded(x-m.width/2-7,y-17,m.width+14,23,7,bg);ctx.fillStyle=fg;ctx.textAlign='center';ctx.fillText(text,x,y);ctx.textAlign='left'}
function tree(x,y,s=1){ctx.fillStyle='#7c4a20';ctx.fillRect(x-6*s,y,12*s,28*s);ctx.fillStyle='#2f9f53';ctx.beginPath();ctx.arc(x,y,25*s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#49b969';ctx.beginPath();ctx.arc(x-12*s,y-7*s,15*s,0,Math.PI*2);ctx.fill()}
function drawStudent(x,y,color='#2563eb',npc=false){ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(0,20,18,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f2bd8c';ctx.beginPath();ctx.arc(0,-14,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1f2937';ctx.beginPath();ctx.arc(0,-17,11,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle=color;rounded(-11,-3,22,27,7,color);ctx.fillStyle='#172554';ctx.fillRect(-10,22,7,12);ctx.fillRect(3,22,7,12);if(!npc){ctx.fillStyle='#f59e0b';rounded(7,2,9,18,4,'#f59e0b')}ctx.restore()}
function drawPortal(x,y,labelText){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#fbbf24';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,26,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.stroke();ctx.restore();label(labelText,x,y-37,'#fff7ed','#9a3412')}
function mapBase(grass='#89cf68'){ctx.fillStyle=grass;ctx.fillRect(0,0,W,H);ctx.fillStyle='#d8c6a3';ctx.fillRect(430,0,100,H);ctx.fillRect(0,360,W,92);ctx.fillStyle='rgba(255,255,255,.12)';for(let x=0;x<W;x+=48)for(let y=0;y<H;y+=48){ctx.fillRect(x+3,y+3,2,2)}}
function drawLevel1(){mapBase();for(const p of [[90,105],[160,470],[820,110],[875,300]])tree(...p);rounded(260,55,440,165,14,'#f6d39b','#7c4a20');ctx.fillStyle='#fff';ctx.fillRect(300,105,360,105);ctx.fillStyle='#65a8e8';for(let i=0;i<5;i++)ctx.fillRect(325+i*65,125,40,35);rounded(455,155,50,65,5,'#8b5e3c');label('SEKOLAH',480,92,'#fff7d6','#7c2d12');rounded(90,275,140,70,12,'#dbeafe','#334155');label('PERPUSTAKAAN',160,305);rounded(750,265,135,80,12,'#bbf7d0','#166534');label('TAMAN',818,300);drawStudent(720,405,'#ef4444',true);label('Nadia',720,365,'#fff','#1e3a8a');if(state.level1)drawPortal(865,465,'Ke Level 2')}
function drawLevel2(){mapBase('#8ed870');for(const p of [[95,115],[180,165],[860,90],[860,300],[100,310]])tree(...p,.9);ctx.fillStyle='#86c7ef';ctx.beginPath();ctx.ellipse(480,130,115,62,0,0,Math.PI*2);ctx.fill();label('TAMAN NILAI',480,62,'#ecfccb','#166534');collectibles.forEach((c,i)=>{if(state.collect.has(i))return;ctx.fillStyle='#fde68a';ctx.beginPath();ctx.arc(c.x,c.y,20,0,Math.PI*2);ctx.fill();ctx.font='24px serif';ctx.textAlign='center';ctx.fillText(c.icon,c.x,c.y+8);ctx.textAlign='left';label(c.label,c.x,c.y-30,'#fff','#166534')});hazards.forEach((h,i)=>{if(state.hazards.has(i))return;ctx.fillStyle='#451a03';rounded(h.x-28,h.y-20,56,40,12,'#451a03');ctx.fillStyle='#fff';ctx.font='20px serif';ctx.textAlign='center';ctx.fillText('👾',h.x,h.y+6);ctx.textAlign='left';label(h.label,h.x,h.y-29,'#fee2e2','#991b1b')});if(state.collect.size===collectibles.length)drawPortal(870,470,'Ke Level 3')}
function drawLevel3(){ctx.fillStyle='#f2e3c2';ctx.fillRect(0,0,W,H);ctx.fillStyle='#c9975b';ctx.fillRect(0,370,W,170);rounded(105,55,750,225,18,'#fff7ed','#9a6b39');label('RUANG MUSYAWARAH',480,92,'#fff','#7c2d12');ctx.fillStyle='#865b3b';rounded(260,195,440,70,16,'#865b3b');for(let x=300;x<=660;x+=90)drawStudent(x,320,x%180===0?'#16a34a':'#7c3aed',true);drawStudent(480,145,'#ef4444',true);label('Ketua Kelas',480,112,'#fff','#1e3a8a');if(state.level3)drawPortal(865,465,'Ke Level 4')}
function drawLevel4(){ctx.fillStyle='#e8f2ff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#c9ab7d';ctx.fillRect(0,400,W,140);for(let y=250;y<=350;y+=90)for(let x=150;x<=750;x+=200){rounded(x,y,130,55,10,'#f4c27a','#855a2b')}rounded(260,70,440,120,10,'#183c2e','#8b5e3c');ctx.fillStyle='#fff';ctx.font='700 27px system-ui';ctx.textAlign='center';ctx.fillText('AKSI NYATA PANCASILA',480,135);ctx.textAlign='left';drawStudent(790,300,'#16a34a',true);label('Guru',790,260);if(state.level4)drawPortal(870,465,'Selesaikan')}
function draw(){ctx.clearRect(0,0,W,H);[drawLevel1,drawLevel2,drawLevel3,drawLevel4][currentLevel]();drawStudent(player.x,player.y,'#2563eb');}
function setPrompt(fn,text){promptAction=fn;promptLabel=text;$("promptText").textContent=text;$("interactPrompt").classList.toggle('hidden',!fn)}
function updatePrompt(){let fn=null,text='';if(currentLevel===0){if(!state.level1&&dist(player,{x:720,y:405})<70){fn=openQuiz1;text='Bicara dengan Nadia'}else if(state.level1&&dist(player,{x:865,y:465})<65){fn=nextLevel;text='Masuk Level 2'}}else if(currentLevel===1){if(state.collect.size===collectibles.length&&dist(player,{x:870,y:470})<65){fn=nextLevel;text='Masuk Level 3'}}else if(currentLevel===2){if(!state.level3&&dist(player,{x:480,y:145})<80){fn=openCouncil;text='Ikuti Musyawarah'}else if(state.level3&&dist(player,{x:865,y:465})<65){fn=nextLevel;text='Masuk Level 4'}}else{if(!state.level4&&dist(player,{x:790,y:300})<80){fn=openActionBuilder;text='Rancang Aksi Nyata'}else if(state.level4&&dist(player,{x:870,y:465})<65){fn=finishGame;text='Selesaikan Petualangan'}}setPrompt(fn,text)}
function interact(){if(paused||modalOpen)return;if(promptAction)promptAction()}
function move(dt){let dx=(keys['d']||keys['arrowright']?1:0)-(keys['a']||keys['arrowleft']?1:0)+joy.x;let dy=(keys['s']||keys['arrowdown']?1:0)-(keys['w']||keys['arrowup']?1:0)+joy.y;const len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len}player.x=Math.max(25,Math.min(W-25,player.x+dx*player.speed*dt));player.y=Math.max(80,Math.min(H-28,player.y+dy*player.speed*dt));if(currentLevel===1)collisionsLevel2();updatePrompt()}
function collisionsLevel2(){collectibles.forEach((c,i)=>{if(!state.collect.has(i)&&dist(player,c)<35){state.collect.add(i);addXp(6);toast(`+6 XP • ${c.label}`);if(state.collect.size===collectibles.length){addXp(1);toast('Semua Nilai Pancasila terkumpul! +1 bonus XP')}}});if(hazardCooldown>0)return;hazards.forEach((h,i)=>{if(!state.hazards.has(i)&&dist(player,h)<38){state.hazards.add(i);hearts=Math.max(1,hearts-1);xp=Math.max(0,xp-2);hazardCooldown=.9;updateHUD();beep(180,.14);toast(`Hindari ${h.label}! -2 XP`)}})}
function routeHint(text){if(student.route==='tantangan')return '';if(student.route==='penguatan')return `<div class="hint-box">💡 Petunjuk: ${text}</div>`;return `<div class="hint-box">💡 Bantuan Jalur Eksplorasi: ${text}</div>`}
function modal(html){$("modalPanel").innerHTML=html;show($("modalOverlay"));modalOpen=true;paused=true}
function closeModal(){hide($("modalOverlay"));modalOpen=false;paused=false}
function openQuiz1(){modal(`<span class="title-badge">🏫 MISI 1 • DETEKTIF NILAI</span><h2>Perbedaan Pendapat di Kelas</h2><div class="npc-line"><span>👧</span><p>“Kelas kami berbeda pendapat tentang pertunjukan. Ada yang memilih tarian daerah, ada juga yang ingin K-Pop. Bagaimana sebaiknya keputusan dibuat?”</p></div><b>Sikap yang paling sesuai nilai Pancasila adalah...</b>${routeHint('Perhatikan apakah semua pihak didengar dan keputusan dicari melalui musyawarah.')}<div class="choices"><button class="choice" data-q1="best">A. Mendengarkan pendapat semua pihak dan mencari solusi bersama</button><button class="choice" data-q1="mid">B. Mengikuti pilihan mayoritas tanpa membahas alasan</button><button class="choice" data-q1="low">C. Membiarkan ketua memilih sendiri agar cepat</button></div>`);document.querySelectorAll('[data-q1]').forEach(b=>b.onclick=()=>{const v=b.dataset.q1;if(v==='best'){addXp(25);b.classList.add('good');toast('+25 XP • Musyawarah')}else if(v==='mid'){addXp(15);b.classList.add('bad');toast('+15 XP • Pilihan cukup, alasan perlu diperkuat')}else{addXp(8);b.classList.add('bad');toast('+8 XP • Coba pikirkan hak semua pihak')}state.level1=true;setTimeout(closeModal,650)})}
function openCouncil(){modal(`<span class="title-badge">🗣️ MISI 3 • RUANG MUSYAWARAH</span><h2>Pilih Solusi yang Paling Bertanggung Jawab</h2><div class="npc-line"><span>🧑‍🎓</span><p>“Sebagian anggota sudah tidak mau ikut persiapan karena keputusan diambil tanpa mendengarkan mereka.”</p></div><b>Apa solusi yang paling tepat?</b>${routeHint('Bandingkan dampak setiap pilihan terhadap martabat, persatuan, dan musyawarah.')}<div class="choices"><button class="choice" data-council="best">A. Buka kembali forum, dengarkan alasan, lalu sepakati bentuk pertunjukan yang menghargai semua pihak</button><button class="choice" data-council="mid">B. Tetap memakai keputusan lama, tetapi minta semua siswa ikut membantu</button><button class="choice" data-council="low">C. Batalkan seluruh kegiatan agar tidak ada konflik</button></div>`);document.querySelectorAll('[data-council]').forEach(b=>b.onclick=()=>{const v=b.dataset.council;if(v==='best'){addXp(25);toast('+25 XP • Solusi beralasan kuat')}else if(v==='mid'){addXp(15);toast('+15 XP • Persatuan diperhatikan, tetapi musyawarah belum pulih')}else{addXp(8);toast('+8 XP • Masalah belum benar-benar diselesaikan')}state.level3=true;setTimeout(closeModal,650)})}
function openActionBuilder(){modal(`<span class="title-badge">🛠️ MISI 4 • BUILDER AKSI</span><h2>Ubah Nilai Menjadi Tindakan Nyata</h2><p>Rancang satu tindakan yang dapat diterapkan di kelas. Empat unsur harus jelas.</p>${routeHint('Gunakan pola: tindakan + siapa + kapan + tanda keberhasilan yang bisa diamati.')}<div class="form-grid"><label>Tindakan<textarea id="aAction" placeholder="Apa yang dilakukan?"></textarea></label><label>Pelaksana<input id="aActor" placeholder="Siapa yang melakukan?" /></label><label>Waktu<input id="aTime" placeholder="Kapan dilakukan?" /></label><label>Indikator<textarea id="aIndicator" placeholder="Apa tanda berhasilnya?"></textarea></label><button class="primary wide" id="saveAction">⚡ Aktifkan Rencana</button></div>`);$("saveAction").onclick=()=>{const d={action:$("aAction").value.trim(),actor:$("aActor").value.trim(),time:$("aTime").value.trim(),indicator:$("aIndicator").value.trim()};if(!d.action||!d.actor||!d.time||!d.indicator){beep(200,.1);toast('Lengkapi keempat unsur rencana.');return}Object.assign(actionData,d);try{localStorage.setItem('pancapath_quest_action',JSON.stringify(d))}catch(e){}addXp(25);state.level4=true;toast('+25 XP • Rencana aksi aktif!');setTimeout(closeModal,650)}}
function getBadge(x){if(x>=90)return'🏅 Pancasila Pathfinder';if(x>=75)return'💡 Civic Problem Solver';if(x>=55)return'🔎 Value Detective';return'🌱 Pancasila Explorer'}
function finishGame(){paused=true;const elapsed=Math.max(1,Math.floor((Date.now()-startTime)/1000));const mm=String(Math.floor(elapsed/60)).padStart(2,'0'),ss=String(elapsed%60).padStart(2,'0');const badge=getBadge(xp);const result={completed:true,xp,badge,route:student.route,source:'adventure',completed_at:new Date().toISOString()};try{localStorage.setItem('pancapath_quest',JSON.stringify(result));if(actionData.action)localStorage.setItem('pancapath_quest_action',JSON.stringify(actionData))}catch(e){}$("finalXp").textContent=`${xp}/100`;$("finalBadge").textContent=badge;$("finalTime").textContent=`${mm}:${ss}`;$("completeText").textContent=`${student.name}, kamu telah menyelesaikan empat level PancaQuest Adventure.`;show($("completeOverlay"));beep(900,.2)}
function returnToPancaPath(){const badge=getBadge(xp);let action='';try{action=JSON.stringify(actionData)}catch(e){}const u=new URL(returnUrl,location.href);u.searchParams.set('quest_xp',String(xp));u.searchParams.set('quest_badge',badge);u.searchParams.set('quest_route',student.route);if(actionData.action)u.searchParams.set('quest_action',action);location.href=u.toString()}
function restartCurrent(){if(currentLevel===0)state.level1=false;if(currentLevel===1){state.collect.clear();state.hazards.clear();hearts=3}if(currentLevel===2)state.level3=false;if(currentLevel===3)state.level4=false;resetPlayer();updateHUD();hide($("pauseOverlay"));paused=false}
function showHelp(){modal(`<h2>📖 Panduan Kontrol</h2><div class="mission-list"><span>💻 WASD / tombol panah = bergerak</span><span>⌨️ E / Space = interaksi</span><span>📱 Joystick kiri = bergerak</span><span>✋ Tombol Aksi = interaksi</span></div><p>Dekati NPC, objek, atau portal sampai muncul tombol interaksi. Selesaikan misi untuk membuka level berikutnya.</p><button class="primary" id="closeHelp">Mengerti</button>`);$("closeHelp").onclick=closeModal}

function loop(t){const dt=Math.min(.035,(t-(loop.last||t))/1000);loop.last=t;if(!paused&&!modalOpen){if(hazardCooldown>0)hazardCooldown-=dt;move(dt)}draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='e'||k===' ')interact();if(k==='escape')togglePause()});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function togglePause(){if(!gameStarted||modalOpen)return;if(paused){hide($("pauseOverlay"));paused=false}else{paused=true;show($("pauseOverlay"))}}
$("startBtn").onclick=()=>{hide($("startOverlay"));gameStarted=true;paused=false;startTime=Date.now();updateHUD();beep(700,.1)};
$("backBeforeBtn").onclick=()=>location.href=returnUrl;$("pauseBtn").onclick=togglePause;$("resumeBtn").onclick=()=>{hide($("pauseOverlay"));paused=false};$("helpBtn").onclick=()=>{hide($("pauseOverlay"));showHelp()};$("restartLevelBtn").onclick=restartCurrent;$("exitBtn").onclick=()=>location.href=returnUrl;$("returnBtn").onclick=returnToPancaPath;
$("soundBtn").onclick=()=>{audioOn=!audioOn;$("soundBtn").textContent=audioOn?'🔊':'🔇'};$("fullBtn").onclick=()=>{const el=$("gameShell");if(!document.fullscreenElement)el.requestFullscreen?.();else document.exitFullscreen?.()};
const joyEl=$("joystick"),knob=$("joyKnob");let joyPointer=null;function setJoy(e){const r=joyEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.31,len=Math.hypot(dx,dy)||1,f=Math.min(1,max/len);dx*=f;dy*=f;knob.style.transform=`translate(${dx}px,${dy}px)`;joy.x=dx/max;joy.y=dy/max}joyEl.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joyEl.setPointerCapture(e.pointerId);setJoy(e)});joyEl.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)setJoy(e)});function endJoy(e){if(e.pointerId!==joyPointer)return;joyPointer=null;joy.x=joy.y=0;knob.style.transform=''}joyEl.addEventListener('pointerup',endJoy);joyEl.addEventListener('pointercancel',endJoy);$("actionBtn").addEventListener('pointerdown',e=>{e.preventDefault();interact()});
updateHUD();draw();
})();